// -------------------------------------------------------------------------------					
//  Value Set. File: 					eHDSIVaccine.fsh
// -------------------------------------------------------------------------------					
ValueSet: EHDSIVaccine					
Id: eHDSIVaccine					
Title: "Vaccine"					
Description: """The Value Set is used to identify the patient's vaccinations in the Patient Summary"""					
* ^url = "http://terminology.ehdsi.eu/ValueSet/eHDSIVaccine"			
* ^status = #active					
* ^experimental = false					
					
* $atc#J07AC  "Anthrax vaccines"					
* $atc#J07AC01  "anthrax antigen"					
* $atc#J07AD  "Brucellosis vaccines"					
* $atc#J07AD01  "brucella antigen"					
* $atc#J07AE  "Cholera vaccines"					
* $atc#J07AE01  "cholera, inactivated, whole cell"					
* $atc#J07AE02  "cholera, live attenuated"					
* $atc#J07AE51  "cholera, combinations with typhoid vaccine, inactivated, whole cell"					
* $atc#J07AF  "Diphtheria vaccines"					
* $atc#J07AF01  "diphtheria toxoid"					
* $atc#J07AG  "Haemophilus influenzae B vaccines"					
* $atc#J07AG01  "haemophilus influenzae B, purified antigen conjugated"					
* $atc#J07AG51  "haemophilus influenzae B, combinations with toxoids"					
* $atc#J07AG52  "haemophilus influenzae B, combinations with pertussis and toxoids"					
* $atc#J07AG53  "haemophilus influenzae B, combinations with meningococcus C, conjugated"					
* $atc#J07AG54  "haemophilus influenza B, combinations with meningococcus C,Y, conjugated"					
* $atc#J07AH  "Meningococcal vaccines"					
* $atc#J07AH01  "meningococcus A, purified polysaccharides antigen"					
* $atc#J07AH02  "other meningococcal monovalent purified polysaccharides antigen"					
* $atc#J07AH03  "meningococcus A,C, bivalent purified polysaccharides antigen"					
* $atc#J07AH04  "meningococcus A,C,Y,W-135, tetravalent purified polysaccharides antigen"					
* $atc#J07AH05  "other meningococcal polyvalent purified polysaccharides antigen"					
* $atc#J07AH06  "meningococcus B, outer membrane vesicle vaccine"					
* $atc#J07AH07  "meningococcus C, purified polysaccharides antigen conjugated"					
* $atc#J07AH08  "meningococcus A,C,Y,W-135, tetravalent purified polysaccharides antigen conjugated"					
* $atc#J07AH09  "meningococcus B, multicomponent vaccine"					
* $atc#J07AH10  "meningococcus A, purified polysaccharides antigen conjugated"					
* $atc#J07AJ  "Pertussis vaccines"					
* $atc#J07AJ01  "pertussis, inactivated, whole cell"					
* $atc#J07AJ02  "pertussis, purified antigen"					
* $atc#J07AJ51  "pertussis, inactivated, whole cell, combinations with toxoids"					
* $atc#J07AJ52  "pertussis, purified antigen, combinations with toxoids"					
* $atc#J07AK  "Plague vaccines"					
* $atc#J07AK01  "plague, inactivated, whole cell"					
* $atc#J07AL  "Pneumococcal vaccines"					
* $atc#J07AL01  "pneumococcus, purified polysaccharides antigen"					
* $atc#J07AL02  "pneumococcus, purified polysaccharides antigen conjugated"					
* $atc#J07AL52  "pneumococcus purified polysaccharides antigen and haemophilus influenzae, conjugated"					
* $atc#J07AM  "Tetanus vaccines"					
* $atc#J07AM01  "tetanus toxoid"					
* $atc#J07AM51  "tetanus toxoid, combinations with diphtheria toxoid"					
* $atc#J07AM52  "tetanus toxoid, combinations with tetanus immunoglobulin"					
* $atc#J07AN  "Tuberculosis vaccines"					
* $atc#J07AN01  "tuberculosis, live attenuated"					
* $atc#J07AP  "Typhoid vaccines"					
* $atc#J07AP01  "typhoid, oral, live attenuated"					
* $atc#J07AP02  "typhoid, inactivated, whole cell"					
* $atc#J07AP03  "typhoid, purified polysaccharide antigen"					
* $atc#J07AP10  "typhoid, combinations with paratyphi types"					
* $atc#J07AR  "Typhus (exanthematicus) vaccines"					
* $atc#J07AR01  "typhus exanthematicus, inactivated, whole cell"					
* $atc#J07AX  "Other bacterial vaccines"					
* $atc#J07AX01  "leptospira vaccines"					
* $atc#J07BA  "Encephalitis vaccines"					
* $atc#J07BA01  "encephalitis, tick borne, inactivated, whole virus"					
* $atc#J07BA02  "encephalitis, Japanese, inactivated, whole virus"					
* $atc#J07BA03  "encephalitis, Japanese, live attenuated"					
* $atc#J07BB  "Influenza vaccines"					
* $atc#J07BB01  "influenza, inactivated, whole virus"					
* $atc#J07BB02  "influenza, inactivated, split virus or surface antigen"					
* $atc#J07BB03  "influenza, live attenuated"					
* $atc#J07BB04  "influenza, virus like particles"					
* $atc#J07BC  "Hepatitis vaccines"					
* $atc#J07BC01  "hepatitis B, purified antigen"					
* $atc#J07BC02  "hepatitis A, inactivated, whole virus"					
* $atc#J07BC20  "combinations"					
* $atc#J07BD  "Measles vaccines"					
* $atc#J07BD01  "measles, live attenuated"					
* $atc#J07BD51  "measles, combinations with mumps, live attenuated"					
* $atc#J07BD52  "measles, combinations with mumps and rubella, live attenuated"					
* $atc#J07BD53  "measles, combinations with rubella, live attenuated"					
* $atc#J07BD54  "measles, combinations with mumps, rubella and varicella, live attenuated"					
* $atc#J07BE  "Mumps vaccines"					
* $atc#J07BE01  "mumps, live attenuated"					
* $atc#J07BF  "Poliomyelitis vaccines"					
* $atc#J07BF01  "poliomyelitis oral, monovalent, live attenuated"					
* $atc#J07BF02  "poliomyelitis oral, trivalent, live attenuated"					
* $atc#J07BF03  "poliomyelitis, trivalent, inactivated, whole virus"					
* $atc#J07BF04  "poliomyelitis oral, bivalent, live attenuated"					
* $atc#J07BG  "Rabies vaccines"					
* $atc#J07BG01  "rabies, inactivated, whole virus"					
* $atc#J07BH  "Rota virus diarrhea vaccines"					
* $atc#J07BH01  "rota virus, live attenuated"					
* $atc#J07BH02  "rota virus, pentavalent, live, reassorted"					
* $atc#J07BJ  "Rubella vaccines"					
* $atc#J07BJ01  "rubella, live attenuated"					
* $atc#J07BJ51  "rubella, combinations with mumps, live attenuated"					
* $atc#J07BK  "Varicella zoster vaccines"					
* $atc#J07BK01  "varicella, live attenuated"					
* $atc#J07BK02  "zoster, live attenuated"					
* $atc#J07BK03  "zoster, purified antigen"					
* $atc#J07BL  "Yellow fever vaccines"					
* $atc#J07BL01  "yellow fever, live attenuated"					
* $atc#J07BM  "Papillomavirus vaccines"					
* $atc#J07BM01  "papillomavirus (human types 6, 11, 16, 18)"					
* $atc#J07BM02  "papillomavirus (human types 16, 18)"					
* $atc#J07BM03  "papillomavirus (human types 6, 11, 16, 18, 31, 33, 45, 52, 58)"					
* $atc#J07BN  "Covid-19 vaccines"					
* $atc#J07BN01  "covid-19, RNA-based vaccine"					
* $atc#J07BN02  "covid-19, viral vector, non-replicating"					
* $atc#J07BN03  "covid-19, inactivated virus"					
* $atc#J07BN04  "covid-19, protein subunit"					
* $atc#J07BX  "Other viral vaccines"					
* $atc#J07BX01  "smallpox vaccines"					
* $atc#J07BX02  "ebola vaccines"					
* $atc#J07BX04  "dengue virus vaccines"					
* $atc#J07CA  "Bacterial and viral vaccines, combined"					
* $atc#J07CA01  "diphtheria-poliomyelitis-tetanus"					
* $atc#J07CA02  "diphtheria-pertussis-poliomyelitis-tetanus"					
* $atc#J07CA03  "diphtheria-rubella-tetanus"					
* $atc#J07CA04  "haemophilus influenzae B and poliomyelitis"					
* $atc#J07CA05  "diphtheria-hepatitis B-pertussis-tetanus"					
* $atc#J07CA06  "diphtheria-haemophilus influenzae B-pertussis-poliomyelitis-tetanus"					
* $atc#J07CA07  "diphtheria-hepatitis B-tetanus"					
* $atc#J07CA08  "haemophilus influenzae B and hepatitis B"					
* $atc#J07CA09  "diphtheria-haemophilus influenzae B-pertussis-poliomyelitis-tetanus-hepatitis B"					
* $atc#J07CA10  "typhoid-hepatitis A"					
* $atc#J07CA11  "diphtheria-haemophilus influenzae B-pertussis-tetanus-hepatitis B"					
* $atc#J07CA12  "diphtheria-pertussis-poliomyelitis-tetanus-hepatitis B"					
* $atc#J07CA13  "diphtheria-haemophilus influenzae B-pertussis-tetanus-hepatitis B-meningococcus A + C"					
* $atc#J07XA  "Parasitic vaccines"					
* $atc#J07XA01  "malaria vaccines"					
* $sct#1001000221103  "Inactivated whole Vibrio cholerae antigen only vaccine product in oral dose form"					
* $sct#1011000221100  "Live attenuated Vibrio cholerae antigen only vaccine product in oral dose form"					
* $sct#1031000221108  "Human poliovirus antigen-containing vaccine product"					
* $sct#1051000221104  "Live attenuated Human poliovirus serotypes 1 and 3 antigens only vaccine product in oral dose form"					
* $sct#1052328007  "Streptococcus pneumoniae Danish serotype 4, 6B, 9V, 14, 18C, 19F, and 23F capsular polysaccharide antigens conjugated only vaccine product"					
* $sct#1081000221109  "Live attenuated Rotavirus antigen only vaccine product"					
* $sct#1101000221104  "Clostridium tetani toxoid antigen-containing vaccine product"					
* $sct#1119254000  "Streptococcus pneumoniae Danish serotype 1, 3, 4, 5, 6A, 6B, 7F, 9V, 14, 18C, 19A, 19F, and 23F capsular polysaccharide antigens only vaccine product"					
* $sct#1119305005  "SARS-CoV-2 antigen vaccine"					
* $sct#1119349007  "SARS-CoV-2 mRNA vaccine"					
* $sct#1121000221106  "Live attenuated Yellow fever virus antigen only vaccine product"					
* $sct#1131000221109  "Vaccine product containing only inactivated whole Rabies lyssavirus antigen"					
* $sct#1157024006  "Inactivated whole SARS-CoV-2 antigen vaccine"					
* $sct#1162643001  "SARS-CoV-2 recombinant spike protein antigen vaccine"					
* $sct#1181000221105  "Influenza virus antigen only vaccine product"					
* $sct#1801000221105  "Streptococcus pneumoniae capsular polysaccharide antigen conjugated only vaccine product"					
* $sct#1861000221106  "Bacillus Calmette-Guerin antigen only vaccine product"					
* $sct#1981000221108  "Neisseria meningitidis serogroup B antigen only vaccine product"					
* $sct#2171000221104  "Salmonella enterica subspecies enterica serovar Typhi capsular polysaccharide unconjugated antigen only vaccine product in parenteral dose form"					
* $sct#2221000221107  "Live attenuated Human alphaherpesvirus 3 only vaccine product"					
* $sct#28531000087107  "COVID-19 vaccine"					
* $sct#29061000087103  "COVID-19 non-replicating viral vector vaccine"					
* $sct#37146000  "Typhus vaccine"					
* $sct#409568008  "Pentavalent botulinum toxoid vaccine"					
* $sct#428601009  "Paratyphoid vaccine"					
* $sct#601000221108  "Bordetella pertussis antigen-containing vaccine product"					
* $sct#774618008  "Whole cell Bordetella pertussis and Clostridium tetani toxoid adsorbed and Corynebacterium diphtheriae toxoid antigens only vaccine product"					
* $sct#775641005  "Clostridium tetani toxoid adsorbed and Corynebacterium diphtheriae toxoid antigens only vaccine product"					
* $sct#777725002  "Clostridium tetani toxoid antigen adsorbed only vaccine product"					
* $sct#836368004  "Bacteria antigen-containing vaccine product"					
* $sct#836369007  "Virus antigen-containing vaccine product"					
* $sct#836374004  "Hepatitis B virus antigen-containing vaccine product"					
* $sct#836375003  "Hepatitis A virus antigen-containing vaccine product"					
* $sct#836377006  "Influenza virus antigen-containing vaccine product"					
* $sct#836378001  "Japanese encephalitis virus antigen-containing vaccine product"					
* $sct#836379009  "Human papillomavirus antigen-containing vaccine product"					
* $sct#836380007  "Haemophilus influenzae type B antigen-containing vaccine product"					
* $sct#836381006  "Corynebacterium diphtheriae antigen-containing vaccine product"					
* $sct#836382004  "Measles morbillivirus antigen-containing vaccine product"					
* $sct#836383009  "Vibrio cholerae antigen-containing vaccine product"					
* $sct#836384003  "Bacillus anthracis antigen-containing vaccine product"					
* $sct#836385002  "Yellow fever virus antigen-containing vaccine product"					
* $sct#836387005  "Rotavirus antigen-containing vaccine product"					
* $sct#836388000  "Rubella virus antigen-containing vaccine product"					
* $sct#836389008  "Vaccinia virus antigen-containing vaccine product"					
* $sct#836390004  "Salmonella enterica subspecies enterica serovar Typhi antigen-containing vaccine product"					
* $sct#836393002  "Rabies lyssavirus antigen-containing vaccine product"					
* $sct#836397001  "Coxiella burnetii antigen-containing vaccine product"					
* $sct#836398006  "Streptococcus pneumoniae antigen-containing vaccine product"					
* $sct#836401009  "Neisseria meningitidis antigen-containing vaccine product"					
* $sct#836402002  "Bacillus Calmette-Guerin antigen-containing vaccine product"					
* $sct#836403007  "Tick-borne encephalitis virus antigen-containing vaccine product"					
* $sct#836495005  "Human alphaherpesvirus 3 antigen-containing vaccine product"					
* $sct#836498007  "Mumps orthorubulavirus antigen-containing vaccine product"					
* $sct#836500008  "Haemophilus influenzae type B and Neisseria meningitidis serogroup C antigens only vaccine product"					
* $sct#840549009  "Yersinia pestis antigen-containing vaccine product"					
* $sct#840563003  "Dengue virus antigen-containing vaccine product"					
* $sct#840599008  "Borrelia burgdorferi antigen-containing vaccine product"					
* $sct#863911006  "Clostridium tetani antigen-containing vaccine product"					
* $sct#871726005  "Rabies lyssavirus antigen only vaccine product"					
* $sct#871737006  "Mumps orthorubulavirus antigen only vaccine product"					
* $sct#871738001  "Live attenuated Mumps orthorubulavirus antigen only vaccine product"					
* $sct#871739009  "Human poliovirus antigen only vaccine product"					
* $sct#871740006  "Inactivated whole Human poliovirus antigen only vaccine product"					
* $sct#871742003  "Clostridium tetani antigen only vaccine product"					
* $sct#871751006  "Hepatitis A virus antigen only vaccine product"					
* $sct#871759008  "Acellular Bordetella pertussis only vaccine product"					
* $sct#871764007  "Haemophilus influenzae type b antigen only vaccine product"					
* $sct#871765008  "Measles morbillivirus antigen only vaccine product"					
* $sct#871768005  "Influenza virus antigen only vaccine product in nasal dose form"					
* $sct#871772009  "Influenza A virus subtype H1N1 antigen only vaccine product"					
* $sct#871803007  "Hepatitis A and Hepatitis B virus antigens only vaccine product"					
* $sct#871804001  "Hepatitis A virus and Salmonella enterica subspecies enterica serovar Typhi antigens only vaccine product"					
* $sct#871806004  "Haemophilus influenzae type B and Hepatitis B virus antigens only vaccine product"					
* $sct#871826000  "Clostridium tetani and Corynebacterium diphtheriae antigens only vaccine product"					
* $sct#871831003  "Measles morbillivirus and Mumps orthorubulavirus and Rubella virus antigens only vaccine product"					
* $sct#871837004  "Clostridium tetani and Corynebacterium diphtheriae and Human poliovirus antigens only vaccine product"					
* $sct#871839001  "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Haemophilus influenzae type B antigens only vaccine product"					
* $sct#871866001  "Neisseria meningitidis serogroup C only vaccine product"					
* $sct#871871008  "Neisseria meningitidis serogroup A and C only vaccine product"					
* $sct#871873006  "Neisseria meningitidis serogroup A, C, W135 and Y only vaccine product"					
* $sct#871875004  "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae antigens only vaccine product"					
* $sct#871876003  "Acellular Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae antigens only vaccine product"					
* $sct#871878002  "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Human poliovirus antigens only vaccine product"					
* $sct#871887006  "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Haemophilus influenzae type B and Human poliovirus antigens only vaccine product"					
* $sct#871889009  "Acellular Bordetella pertussis and Corynebacterium diphtheriae and Hepatitis B virus and inactivated whole Human poliovirus antigens only vaccine product"					
* $sct#871895005  "Bordetella pertussis and Clostridium tetani and Corynebacterium diphtheriae and Haemophilus influenzae type B and Hepatitis B virus and Human poliovirus antigens only vaccine product"					
* $sct#871908002  "Human alphaherpesvirus 3 and Measles morbillivirus and Mumps orthorubulavirus and Rubella virus antigens only vaccine product"					
* $sct#871918007  "Rickettsia antigen-containing vaccine product"					
* $sct#871921009  "Staphylococcus toxoid vaccine"					
* $sct#921000221108  "Neisseria meningitidis antigen only vaccine product"					
* $sct#971000221109  "Live attenuated Salmonella enterica subspecies enterica serovar Typhi antigen only vaccine product in oral dose form"					
* $sct#981000221107  "Streptococcus pneumoniae antigen only vaccine product"					
//---END					
//---END					
//---END					
